In [1]:
# pandas, numpy, matplotlib.pyplot, seaborn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
print(np.__version__)

1.20.1


In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [7]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [9]:
np.empty((4,4))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        6.39784051e-307],
       [2.22522597e-306, 1.33511969e-306, 1.37962320e-306,
        9.34604358e-307],
       [9.79101082e-307, 1.78020576e-306, 1.69119873e-306,
        2.22522868e-306],
       [1.24611809e-306, 8.06632139e-308, 1.60221208e-306,
        2.29178686e-312]])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [16]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
arr.shape
#행열 개념보다 차원 축 개념으로 접근
#오른쪽부터 작은 차원 축

(2, 3)

In [14]:
arr.ndim

2

In [15]:
arr.dtype

dtype('int32')

In [20]:
def cp(arr):
    print("type:{}".format(type(arr)))
    print("shape:{}, dim:{}, dtype:{}".format(arr.shape, arr.ndim, arr.dtype))
    print("arr data : \n", arr)

In [21]:
cp(arr)

type:<class 'numpy.ndarray'>
shape:(2, 3), dim:2, dtype:int32
arr data : 
 [[1 2 3]
 [4 5 6]]


In [23]:
np.arange(1, 7).reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
a1 = np.arange(1,7)
a2 = np.arange(1,7).reshape(-1,3)
a3 = np.arange(1,25).reshape(2,3,-1)
a4 = np.arange(1,49).reshape(2,2,3,4)

In [27]:
cp(a1)
#shape는 2차원 기준 출력이라 앞자리에 개수 표시

type:<class 'numpy.ndarray'>
shape:(6,), dim:1, dtype:int32
arr data : 
 [1 2 3 4 5 6]


In [28]:
cp(a2)

type:<class 'numpy.ndarray'>
shape:(2, 3), dim:2, dtype:int32
arr data : 
 [[1 2 3]
 [4 5 6]]


In [29]:
cp(a3)

type:<class 'numpy.ndarray'>
shape:(2, 3, 4), dim:3, dtype:int32
arr data : 
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [35]:
cp(a4)

type:<class 'numpy.ndarray'>
shape:(2, 2, 3, 4), dim:4, dtype:int32
arr data : 
 [[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]

  [[13 14 15 16]
   [17 18 19 20]
   [21 22 23 24]]]


 [[[25 26 27 28]
   [29 30 31 32]
   [33 34 35 36]]

  [[37 38 39 40]
   [41 42 43 44]
   [45 46 47 48]]]]


In [36]:
arr_int = np.arange(1,5)
arr_int.dtype

dtype('int32')

In [41]:
arr_float = arr_int.astype(np.float64)
arr_float.dtype

dtype('float64')

In [46]:
arr_str = np.array(["1","2","3"])
arr_str.dtype

dtype('<U1')

In [47]:
arr_int64 = arr_str.astype(np.int64)
arr_int64

array([1, 2, 3], dtype=int64)

In [52]:
arr1 = np.arange(1,5).reshape(2,2)
arr2 = np.arange(5,9).reshape(2,2)

In [53]:
arr1 + arr2

array([[ 6,  8],
       [10, 12]])

In [54]:
np.add(arr1,arr2)

array([[ 6,  8],
       [10, 12]])

In [55]:
arr1 * arr2

array([[ 5, 12],
       [21, 32]])

In [56]:
np.multiply(arr1,arr2)

array([[ 5, 12],
       [21, 32]])

In [57]:
np.divide(arr1,arr2)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [58]:
np.subtract(arr1, arr2)

array([[-4, -4],
       [-4, -4]])

In [59]:
-np.subtract(arr1,arr2)

array([[4, 4],
       [4, 4]])

In [60]:
arr1.dot(arr2)

array([[19, 22],
       [43, 50]])

In [61]:
np.dot(arr1,arr2)

array([[19, 22],
       [43, 50]])

In [63]:
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
arr[:2,1:3]

array([[2, 3],
       [5, 6]])

In [66]:
arr[0,2]

3

In [76]:
arr[arr>3].reshape(2,3)

array([[4, 5, 6],
       [7, 8, 9]])

In [77]:
arr.sum()

45

In [82]:
arr.max()

9

In [81]:
arr.max(axis=0)

array([7, 8, 9])

In [83]:
arr.max(axis=1)

array([3, 6, 9])

In [79]:
arr.min()

1

In [80]:
arr.mean()

5.0

In [84]:
arr.sort();arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
b = arr.copy()

In [87]:
b[1,:]

array([4, 5, 6])

In [88]:
b.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])